### ISSUE TITLE
Ajouter une possibilité qui désactive la notification ?

### ISSUE THREAD

**Issue by Tairox** [Kocal/Solary#64]
Salut, je suis un viewer régulier de Solary : j'ai donc l'extension mais la notification récurrente à chaque lancement de mon Chrome m'agace un peu : j'aimerais profiter du ON/OFF et du bouton cliquable mais sans cette notif !

Merci d'avance.

**Comment by Tairox** [comment]
J'ai fail sur le titre mais tu m'as sûrement compris :D

**Comment by Kocal** [comment]
Salut :slightly_smiling_face: 

Ouaip je comprend, c'est vrai que ça me le fait aussi et ça peut devenir vite embêtant (surtout quand j'ai Alderiate/Kamel/Aayley qui streame, ça m'ouvre 4 notifications ...)

Je vais réfléchir à un système de configuration qui s'intègre bien à l'extension (dans une page Option à part, ou alors dans la popup).

Pour l'instant, j'envisage d'ajouter deux options pour contrôler les notifications : 
1. Ne pas afficher les notifications (ça affiche aucune notifications)
2. Ne pas afficher les notifications à l'ouverture du navigateur (ça cache les notifs quant tu ouvres ton browser, mais ça les affiche lorsqu'un stream démarre un peu plus tard)

Petite remarque, si l'option 1 est cochée, alors il est n'est plus possible de configurer l'option 2. 
Si l'option 1 est décochée, alors on peut de nouveau configurer l'option 2.

Qu'en penses-tu ?

**Comment by Tairox** [comment]
Salut,

Ça me fait clairement chier de répondre à ton message bien fourni par un si petit message mais j'approuve totalement l'idée.

J'ai quand même pensé à la possibilité d'envoyer une notification seulement au changement de titre du stream ou changement de programme sur le planning (options qui pourraient être compatible avec ton option 2).

Voilà voilà, ça fait plaisir d'avoir quelqu'un d'actif !

**Comment by Kocal** [comment]
Pas de soucis 😋

Alors ça c'était déjà prévu dans les 1ère versions, mais je l'ai supprimé lorsque Chap m'a dit qu'ils trouvaient la feature trop utile.
Au final, je pense que je re-introduirait la feature, mais elle sera désactivée par défaut

**Comment by Kocal** [comment]
Je ferme cette issue en faveur de #65

**Comment by Kocal** [comment]
Yop, juste pour te dire que j'ai pu terminer l'implémentation de paramétrage
